//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.OE.Data.Models.Pdspayments
{
   [ModelName("Infor.Sxe.OE.Data.Models.Pdspayments.Paymentnumbers")]
   public partial class Paymentnumbers : ModelBase
   {
      public int iMediaCd { get; set; }
      [StringValidationAttribute]
      public string cPaymentNo { get; set; }
      [StringValidationAttribute]
      public string cUnmaskCardNo { get; set; }
      [StringValidationAttribute]
      public string cCardholderName { get; set; }
      [StringValidationAttribute]
      public string cShipto { get; set; }
      public bool lIsCreditCard { get; set; }
      public bool lIsACH { get; set; }
      public decimal dMinSale { get; set; }
      public bool lCCEnabled { get; set; }
      public bool lAddCardEnabled { get; set; }
      public bool lModifyCardEnabled { get; set; }
      public decimal deCCAddon { get; set; }
      [StringValidationAttribute]
      public string cCCAddonType { get; set; }
      [StringValidationAttribute]
      public string rowidARSD { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Paymentnumbers BuildPaymentnumbersFromRow(DataRow row)
      {
         Paymentnumbers entity = new Paymentnumbers();
         entity.iMediaCd = row.IsNull("iMediaCd") ? 0 : row.Field<int>("iMediaCd");
         entity.cPaymentNo = row.IsNull("cPaymentNo") ? string.Empty : row.Field<string>("cPaymentNo");
         entity.cUnmaskCardNo = row.IsNull("cUnmaskCardNo") ? string.Empty : row.Field<string>("cUnmaskCardNo");
         entity.cCardholderName = row.IsNull("cCardholderName") ? string.Empty : row.Field<string>("cCardholderName");
         entity.cShipto = row.IsNull("cShipto") ? string.Empty : row.Field<string>("cShipto");
         entity.lIsCreditCard = row.Field<bool>("lIsCreditCard");
         entity.lIsACH = row.Field<bool>("lIsACH");
         entity.dMinSale = row.IsNull("dMinSale") ? decimal.Zero : row.Field<decimal>("dMinSale");
         entity.lCCEnabled = row.Field<bool>("lCCEnabled");
         entity.lAddCardEnabled = row.Field<bool>("lAddCardEnabled");
         entity.lModifyCardEnabled = row.Field<bool>("lModifyCardEnabled");
         entity.deCCAddon = row.IsNull("deCCAddon") ? decimal.Zero : row.Field<decimal>("deCCAddon");
         entity.cCCAddonType = row.IsNull("cCCAddonType") ? string.Empty : row.Field<string>("cCCAddonType");
         entity.rowidARSD = row.Field<byte[]>("rowidARSD").ToStringEncoded();
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromPaymentnumbers(ref DataRow row, Paymentnumbers entity)
      {
         row.SetField("iMediaCd", entity.iMediaCd);
         row.SetField("cPaymentNo", entity.cPaymentNo);
         row.SetField("cUnmaskCardNo", entity.cUnmaskCardNo);
         row.SetField("cCardholderName", entity.cCardholderName);
         row.SetField("cShipto", entity.cShipto);
         row.SetField("lIsCreditCard", entity.lIsCreditCard);
         row.SetField("lIsACH", entity.lIsACH);
         row.SetField("dMinSale", entity.dMinSale);
         row.SetField("lCCEnabled", entity.lCCEnabled);
         row.SetField("lAddCardEnabled", entity.lAddCardEnabled);
         row.SetField("lModifyCardEnabled", entity.lModifyCardEnabled);
         row.SetField("deCCAddon", entity.deCCAddon);
         row.SetField("cCCAddonType", entity.cCCAddonType);
         row.SetField("rowidARSD", entity.rowidARSD.ToByteArray());
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
