//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 6149 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using ServiceInterfaceClient.Attributes;

namespace Infor.Sxe.AR.Data.Models.Complex
{
   using Models.Pdsarececheckdata;
   using Models.Pdsarececoddata;
using Models.Pdsareceglobaldata;
using Models.Pdsareceinvoicesdata;
using Models.Pdsareceinvoiceslist;
using Models.Pdsarecemaindata;
using Models.Pdsarecemisccashdata;
using Models.Pdsarecesimcdiv;
using Models.Pdsareceupdatedata;
using Models.Pdsarecewodata;
using Models.Pdsareceworeport;
using Models.Pdsglopenjournal;
using Models.Pdsmessaging;

   public partial class AsarentryARECEUpdateProcessResponseAPI
   {
      public List<Arececoddata> arececoddata { get; set; }
      public List<Areceinvoiceslist> areceinvoiceslist { get; set; }
      public List<Arecesimcdiv> arecesimcdiv { get; set; }
      public List<Arecewodata> arecewodata { get; set; }
      public List<Areceworeport> areceworeport { get; set; }
      public List<Messaging> messaging { get; set; }
      public Arececheckdata arececheckdata { get; set; }
      public Areceglobaldata areceglobaldata { get; set; }
      public Areceinvoicesdata areceinvoicesdata { get; set; }
      public Arecemaindata arecemaindata { get; set; }
      public Arecemisccashdata arecemisccashdata { get; set; }
      public Areceupdatedata areceupdatedata { get; set; }
      public Glopenjournalcriteria glopenjournalcriteria { get; set; }
      public Glopenjournalresults glopenjournalresults { get; set; }
 
    
      public AsarentryARECEUpdateProcessResponseAPI()
      {
         this.arececoddata = new List<Arececoddata>(); 
         this.areceinvoiceslist = new List<Areceinvoiceslist>(); 
         this.arecesimcdiv = new List<Arecesimcdiv>(); 
         this.arecewodata = new List<Arecewodata>(); 
         this.areceworeport = new List<Areceworeport>(); 
         this.messaging = new List<Messaging>(); 

      }
   }
}
#pragma warning restore 1591
