//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 7622 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Web.Http;
using ServiceInterfaceClient.BaseClasses;
    
namespace Infor.Sxe.Web.FrontEnd.Controllers.WebAPI.Data.AP
{  
   using Sxe.AP.Data.Models.PdsContext;
   using Sxe.AP.Data.Models.Pdsapss;
   using Sxe.AP.Data.Models.Pdsapshipfromlookup;
   using Sxe.AP.Data.Models.Complex;
   using Sxe.AP.Data.Repositories;
    
   [RoutePrefix("api/ap/apss")]
   public partial class ApssApiController : ApiControllerBase
   {
      private readonly ApssRepository repository;
    
      public ApssApiController(ApssRepository repository)
      {
         this.repository = repository;
         this.OnCreated();
      }
    
      partial void OnCreated();
    
    
      [HttpGet]
      [Route("getbyrowid/{rowid:maxLength(30)}")]
      public Apss GetByRowId(string rowid, string fldlist = "")
      {
         if (string.IsNullOrEmpty(rowid))
         {
            return null;
         }
         return this.repository.GetByRowId(rowid, fldlist);
      }
      
      [HttpPost]
      [Route("listbyrowids")]      
      public IEnumerable<Apss> GetListByRowIdList(List<string> rowids, string fldlist = "")
      {
         if (rowids == null || rowids.Count == 0)
         {
            return new List<Apss>();
         }
         return this.repository.GetListByRowIdList(rowids, rowids.Count, fldlist);
      }
        
      [HttpGet]
      [Route("")]
      public IEnumerable<Apss> GetListAllByCono(int batchsize = 0, string fldlist = "")
      {  
         return this.repository.GetListAllByCono(0, batchsize, fldlist);
      }
      [HttpPost]
      [Route("listbyrowpointers")] 
      public IEnumerable<Apss> GetListByRowpointers(List<string> rowpointers, string fldlist)
      {
         if (rowpointers == null || rowpointers.Count == 0)
         {
            return new List<Apss>();
         }	  
         return this.repository.GetListByRowpointers(rowpointers, fldlist);
      }
	  
	  
      [HttpGet]
      [Route("getbypk")]
      public Apss Get(decimal vendno = 0, int shipfmno = 0, string fldlist = "")
      {
         return this.repository.Get(0, vendno, shipfmno, 1, fldlist);
      }
        
      [HttpGet]
      [Route("existsbypk")]
      public bool Exists(decimal vendno = 0, int shipfmno = 0)
      {
         return (this.repository.Get(0, vendno, shipfmno, 1, string.Empty) != null);
      }

      [HttpGet]
      [Route("existsbyrowid/{rowid:maxLength(30)}")]
      public bool ExistsByRowId(string rowid)
      {
         if (string.IsNullOrEmpty(rowid))
         {
            return false;
         }
         return (this.repository.GetByRowId(rowid, string.Empty) != null);
      }
	  

      [HttpGet]
      [Route("existsbyrowpointer/{rowpointer:guid}")]
      public bool ExistsByRowpointer(string rowpointer)
      {
         if (string.IsNullOrEmpty(rowpointer))
         {
            return false;
         }
         return (this.repository.GetByRowpointer(rowpointer, string.Empty) != null);
      }
	  
	  
      [HttpGet]
      [Route("listbyaddr")]
      public IEnumerable<Apss> GetListByAddr(decimal vendno = 0, string state = "", string city = "",  int batchsize = 0, string fldlist = "")
      {
         return this.repository.GetListByAddr(0, vendno, state, city, batchsize, fldlist);
      }

      [HttpGet]
      [Route("listbyphone")]
      public IEnumerable<Apss> GetListByPhone(string phoneno = "",  int batchsize = 0, string fldlist = "")
      {
         return this.repository.GetListByPhone(0, phoneno, batchsize, fldlist);
      }

      [HttpGet]
      [Route("getbyrowpointer/{rowpointer:guid}")]
      public Apss GetByRowpointer(string rowpointer, string fldlist = "")
      {
         return this.repository.GetByRowpointer(rowpointer, fldlist);
      }

      [HttpGet]
      [Route("listbytransdttmz")]
      public IEnumerable<Apss> GetListByTransdttmz(DateTime? transdttmz = null,  int batchsize = 0, string fldlist = "")
      {
         return this.repository.GetListByTransdttmz(transdttmz, batchsize, fldlist);
      }

      [HttpGet]
      [Route("listbyzipcd")]
      public IEnumerable<Apss> GetListByZipcd(string zipcd = "", decimal vendno = 0, int shipfmno = 0,  int batchsize = 0, string fldlist = "")
      {
         return this.repository.GetListByZipcd(0, zipcd, vendno, shipfmno, batchsize, fldlist);
      }

      [HttpPost]
      [Route("")]
      public Apss Insert(Apss record)
      {
         return this.repository.Insert(record);
      }
      
      [HttpPut]
      [Route("")]
      public Apss Update(Apss record)
      {
         return this.repository.Update(record);
      }
      
      [HttpDelete]
      [Route("")]
      public void Delete(Apss record)
      {
         this.repository.Delete(record);
      }
  
      [HttpDelete]
      [Route("deletelistbyrowids")]
      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds == null || rowIds.Count == 0)
         {
            return;
         }
         this.repository.DeleteListByRowIds(rowIds);
      }
	   
	  
      [HttpDelete]
      [Route("deletelistbyrowpointers")]
      public void DeleteListByRowPointers(List<string> rowpointers)
      {
         if (rowpointers == null || rowpointers.Count == 0)
         {
            return;
         }
         this.repository.DeleteListByRowPointers(rowpointers);
      }
	  
      
      [Route("lookup")]
      [HttpPost]
      public ApssLookupResponseAPI Lookup(Apshipfromlookupcriteria apshipfromlookupcriteria)
      {
         return this.repository.Lookup(apshipfromlookupcriteria);
      } 
  

      [HttpGet]
      [Route("listbywordindex")]
      public IEnumerable<Apss> GetListByWordIndex(string term = "", int batchsize = 0, string fldlist = "")
      {
         return this.repository.GetListByWordIndex(term, batchsize, fldlist);
      }
  
      protected override void Dispose(bool disposing)
      {
         if (!disposing)
         {
            return;
         }
         this.repository?.Dispose();
         base.Dispose(true);
      }
   }   
}
#pragma warning restore 1591
  