//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using NLog;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.BP.Data.Adapters
{
   using com.infor.sxproxy.bpproxy;
   using com.infor.sxproxy.bpproxy.StrongTypesNS;
    
   using Models.PdsContext;
   using Models.Pdsbpsi;

   public partial class BpsiAdapter : AdapterBase<pdsContextDataSet>
   {
      private const string DataSetName = "pdsbpsi";
      private BPProxyAppObject proxyAppObject;
      private readonly Tuple<string, string> bpsiTableControlKey;
		
      private pdsbpsiDataSet dataSet;
        
      public BpsiAdapter(IProgressConnection connection) : base(connection)
      {
         try 
         {
            this.proxyAppObject = new BPProxyAppObject(connection.Connection);
            this.pdsContext = new pdsContextDataSet();
            this.dataSet = new pdsbpsiDataSet() { DataSetName = DataSetName };
            this.bpsiTableControlKey = this.dataSet.ttblbpsi.GetTableControlParametersKey();
            
            if (!this.tempTableControlParameters.ContainsKey(this.bpsiTableControlKey))
            {
               this.CreateTableControlParameters(this.bpsiTableControlKey);
            }
            this.OnCreated();
         }
         catch (Exception ex)
         {
            NLogLogger.ErrorException("Failed in adapter ", ex);
            ErrorReportingHelper.ReportProgramErrors($"Error in BpsiAdapter constructor - {ex.Message}");
         }
      }
  
      partial void OnCreated();
    
      protected void FetchWhere(string where, int batchsize, string fldList)
      {
         NLogLoggerP.Trace("Fetchwhere - Bpsiproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               this.SetAndFetch(where, batchsize == 0 ? DefaultFetchWhereRowCount : batchsize, fldList);
               using (var poBpsiproxy = this.proxyAppObject.CreatePO_bpsiproxy())
               {
                  var cErrorMessage = string.Empty;
                  this.SetRequiredContextParameters();
                  poBpsiproxy.FetchWhere(ref this.pdsContext, out this.dataSet, out cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("Fetchwhere - Bpsiproxy - After Call");
      }
      
      private void SetAndFetch(string where, int batchsize, string fldList)
      {
         MappedDiagnosticsContext.Set("where", where);
         this.SetFetchWhereParameters(this.bpsiTableControlKey, where, batchsize, fldList);
         this.SetTableParametersOnContext(this.bpsiTableControlKey, true);
      }
  
      protected void SaveChanges()
      {
         NLogLoggerP.Trace("SaveChanges - Bpsiproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poBpsiproxy = this.proxyAppObject.CreatePO_bpsiproxy())
               {
                  this.SetRequiredContextParameters();
                  poBpsiproxy.SaveChanges(ref this.pdsContext, ref this.dataSet, out string cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("SaveChanges - Bpsiproxy - After Call");
      }
   

      public Bpsi GetByRowId(string rowId, string fldList)
      {
         var row = this.GetRowByRowId(rowId, fldList);
         Bpsi bpsi = null;
         if (row != null)
         {
             bpsi = this.BuildFromRow(row);
         }
         return bpsi;
      }
   
      private DataRow GetRowByRowId(string rowId, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("rowid(bpsi) = to-rowid('0x{0}')", rowId.ToClauseString());
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttblbpsi.AsEnumerable().SingleOrDefault();
      }
        
      public IEnumerable<Bpsi> GetListByRowIdList(List<string> rowIds, int batchsize, string fldList)
      {
         var where = new StringBuilder();
         if (rowIds != null && rowIds.Count > 0)
         {
           foreach (var rowId in rowIds)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("rowid(bpsi)=to-rowid('0x{0}')", rowId.ToClauseString());
           }
         }
         return this.GetList(where.ToString(), batchsize, fldList);
      }

      protected Bpsi Fetch(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         var row = this.dataSet.ttblbpsi.AsEnumerable().SingleOrDefault();
         Bpsi bpsi = null;
         if (row != null)
         {
             bpsi = this.BuildFromRow(row);
         }
         return bpsi;
      }
	  
	  
      public IEnumerable<Bpsi> GetListAllByCono(int cono, int batchsize, string fldList)
      {   
         cono = cono == 0 ? this.connection.CompanyNumber : cono;
         var sb = new StringBuilder();
         sb.AppendFormat("bpsi.cono = {0}", cono);
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Bpsi> GetList(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         return (from DataRow row in this.dataSet.ttblbpsi.Rows where row != null select this.BuildFromRow(row)).ToList();
      }

      public Bpsi Get(int cono, string itemid, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("bpsi.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(itemid)) 
         {
             sb.AppendFormatWithEscape(" AND bpsi.itemid = '{0}'", itemid);
         }
         var where = sb.ToString();
         return this.Fetch(where, batchsize, fldList);
      }
  
      public Bpsi BuildFromRow(DataRow row)
      {
         var returnRecord = Bpsi.BuildBpsiFromRow(row);
         returnRecord = this.BuildExtraFromRow<Bpsi>(returnRecord, row);
         return returnRecord;
      }
      
      public void UpdateToRow(ref DataRow row, Bpsi record)
      {
         Bpsi.UpdateRowFromBpsi(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
      }
      
      public Bpsi Insert(Bpsi record)
      {
         DataRow row = this.dataSet.ttblbpsi.NewttblbpsiRow();
         this.UpdateToRow(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
         this.dataSet.ttblbpsi.AddttblbpsiRow((pdsbpsiDataSet.ttblbpsiRow)row);
         this.SaveChanges();
         return this.dataSet.ttblbpsi.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblbpsi.Rows[0]) : null;
      }
  

      public Bpsi Update(Bpsi record)
      {
        var row = this.GetRowByRowId(record.rowID, string.Empty);
         if (row != null)
         {
            this.UpdateToRow(ref row, record);
            this.ExtraUpdateToRow(ref row, record);
            this.SaveChanges();
            return this.dataSet.ttblbpsi.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblbpsi.Rows[0]) : null;
         }
         ErrorReportingHelper.ReportErrors("global.update.doesnotexist", 421);
         return null;
      }
  
      public void Delete(Bpsi record)
      {
         var row = this.GetRowByRowId(record.rowID, string.Empty);         
         if (row == null)
         {
            row = this.dataSet.ttblbpsi.NewttblbpsiRow();
            Bpsi.BuildMinimalRow(ref row, record);
            this.dataSet.ttblbpsi.AddttblbpsiRow((pdsbpsiDataSet.ttblbpsiRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }

      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds != null)
         {
            var recList = rowIds.Select(selectRowId => new Bpsi() { rowID = selectRowId }).ToList();
            foreach (var rec in recList)
            {
               this.Delete(rec);
            }
         }
      }
	  

      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }	
         this.proxyAppObject?.Dispose();

         this.dataSet?.Dispose();
         base.Dispose(true);
      }
  
   }
}
#pragma warning restore 1591
  