//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.IC.Data.Models.Pdsicsewloadtt
{
   [ModelName("Infor.Sxe.IC.Data.Models.Pdsicsewloadtt.Icsewloadttcriteria")]
   public partial class Icsewloadttcriteria : ModelBase
   {
      [StringValidationAttribute]
      public string whse { get; set; }
      [StringValidationAttribute]
      public string whse2 { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Icsewloadttcriteria BuildIcsewloadttcriteriaFromRow(DataRow row)
      {
         Icsewloadttcriteria entity = new Icsewloadttcriteria();
         entity.whse = row.IsNull("whse") ? string.Empty : row.Field<string>("whse");
         entity.whse2 = row.IsNull("whse2") ? string.Empty : row.Field<string>("whse2");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromIcsewloadttcriteria(ref DataRow row, Icsewloadttcriteria entity)
      {
         row.SetField("whse", entity.whse);
         row.SetField("whse2", entity.whse2);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
