//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.OE.Data.Models.Pdsoeipaltprodload
{
   [ModelName("Infor.Sxe.OE.Data.Models.Pdsoeipaltprodload.Oeipaltprodloadresults")]
   public partial class Oeipaltprodloadresults : ModelBase
   {
      public int cono { get; set; }
      [StringValidationAttribute]
      public string rectype { get; set; }
      [StringValidationAttribute]
      public string altprod { get; set; }
      [StringValidationAttribute]
      public string altprodnote { get; set; }
      [StringValidationAttribute]
      public string descrip { get; set; }
      public int qtyavail { get; set; }
      [StringValidationAttribute]
      public string unit { get; set; }


      public static Oeipaltprodloadresults BuildOeipaltprodloadresultsFromRow(DataRow row)
      {
         Oeipaltprodloadresults entity = new Oeipaltprodloadresults();
         entity.cono = row.IsNull("cono") ? 0 : row.Field<int>("cono");
         entity.rectype = row.IsNull("rectype") ? string.Empty : row.Field<string>("rectype");
         entity.altprod = row.IsNull("altprod") ? string.Empty : row.Field<string>("altprod");
         entity.altprodnote = row.IsNull("altprodnote") ? string.Empty : row.Field<string>("altprodnote");
         entity.descrip = row.IsNull("descrip") ? string.Empty : row.Field<string>("descrip");
         entity.qtyavail = row.IsNull("qtyavail") ? 0 : row.Field<int>("qtyavail");
         entity.unit = row.IsNull("unit") ? string.Empty : row.Field<string>("unit");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromOeipaltprodloadresults(ref DataRow row, Oeipaltprodloadresults entity)
      {
         row.SetField("cono", entity.cono);
         row.SetField("rectype", entity.rectype);
         row.SetField("altprod", entity.altprod);
         row.SetField("altprodnote", entity.altprodnote);
         row.SetField("descrip", entity.descrip);
         row.SetField("qtyavail", entity.qtyavail);
         row.SetField("unit", entity.unit);

      }
   
   }
}
#pragma warning restore 1591
