//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.PD.Data.Models.Pdspdemlookup
{
   [ModelName("Infor.Sxe.PD.Data.Models.Pdspdemlookup.Pdemlookupresults")]
   public partial class Pdemlookupresults : ModelBase
   {
      [StringValidationAttribute]
      public string setid { get; set; }
      [StringValidationAttribute]
      public string description { get; set; }
      [StringValidationAttribute]
      public string destination { get; set; }
      [StringValidationAttribute]
      public string destinationdesc { get; set; }
      [StringValidationAttribute]
      public string source { get; set; }
      [StringValidationAttribute]
      public string sourcedesc { get; set; }
      public int stagecd { get; set; }
      [StringValidationAttribute]
      public string stagedesc { get; set; }
      public decimal lastseqno { get; set; }
      public int linecount { get; set; }
      [StringValidationAttribute]
      public string rowidPdem { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Pdemlookupresults BuildPdemlookupresultsFromRow(DataRow row)
      {
         Pdemlookupresults entity = new Pdemlookupresults();
         entity.setid = row.IsNull("setid") ? string.Empty : row.Field<string>("setid");
         entity.description = row.IsNull("description") ? string.Empty : row.Field<string>("description");
         entity.destination = row.IsNull("destination") ? string.Empty : row.Field<string>("destination");
         entity.destinationdesc = row.IsNull("destinationdesc") ? string.Empty : row.Field<string>("destinationdesc");
         entity.source = row.IsNull("source") ? string.Empty : row.Field<string>("source");
         entity.sourcedesc = row.IsNull("sourcedesc") ? string.Empty : row.Field<string>("sourcedesc");
         entity.stagecd = row.IsNull("stagecd") ? 0 : row.Field<int>("stagecd");
         entity.stagedesc = row.IsNull("stagedesc") ? string.Empty : row.Field<string>("stagedesc");
         entity.lastseqno = row.IsNull("lastseqno") ? decimal.Zero : row.Field<decimal>("lastseqno");
         entity.linecount = row.IsNull("linecount") ? 0 : row.Field<int>("linecount");
         entity.rowidPdem = row.Field<byte[]>("rowid-pdem").ToStringEncoded();
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromPdemlookupresults(ref DataRow row, Pdemlookupresults entity)
      {
         row.SetField("setid", entity.setid);
         row.SetField("description", entity.description);
         row.SetField("destination", entity.destination);
         row.SetField("destinationdesc", entity.destinationdesc);
         row.SetField("source", entity.source);
         row.SetField("sourcedesc", entity.sourcedesc);
         row.SetField("stagecd", entity.stagecd);
         row.SetField("stagedesc", entity.stagedesc);
         row.SetField("lastseqno", entity.lastseqno);
         row.SetField("linecount", entity.linecount);
         row.SetField("rowid-pdem", entity.rowidPdem.ToByteArray());
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
