//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 6149 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using ServiceInterfaceClient.Attributes;

namespace Infor.Sxe.OE.Data.Models.Complex
{
   using Models.Pdsoeiolines;

   public partial class AsoelineOELinePriceCostWorkSheetInitRequestAPI
   {
      public List<Oeiolinesresults> oeiolinesresults { get; set; }
      public int pvOrderno { get; set; }
      public int pvOrdersuf { get; set; }
      [StringValidation]
      public string pvProcty { get; set; }
      [StringValidation]
      public string pvMaint { get; set; }
 
    
      public AsoelineOELinePriceCostWorkSheetInitRequestAPI()
      {
         this.oeiolinesresults = new List<Oeiolinesresults>(); 

      }
   }
}
#pragma warning restore 1591
