//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 6149 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using ServiceInterfaceClient.Attributes;

namespace Infor.Sxe.OE.Data.Models.Complex
{
   using Models.Pdsoelineoptprod;

   public partial class AsoelineOELineOptProdUpdateRequestAPI
   {
      public List<Oelineoptprodresults> oelineoptprodresults { get; set; }
      public Oelineoptprod oelineoptprod { get; set; }
 
    
      public AsoelineOELineOptProdUpdateRequestAPI()
      {
         this.oelineoptprodresults = new List<Oelineoptprodresults>(); 

      }
   }
}
#pragma warning restore 1591
