//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.IC.Data.Models.Pdsicebbuildprodlist
{
   [ModelName("Infor.Sxe.IC.Data.Models.Pdsicebbuildprodlist.Icebbuildprodlistcriteria")]
   public partial class Icebbuildprodlistcriteria : ModelBase
   {
      [StringValidationAttribute]
      public string whse { get; set; }
      [StringValidationAttribute]
      public string fromprod { get; set; }
      [StringValidationAttribute]
      public string toprod { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }
      public int recordcountlimit { get; set; }


      public static Icebbuildprodlistcriteria BuildIcebbuildprodlistcriteriaFromRow(DataRow row)
      {
         Icebbuildprodlistcriteria entity = new Icebbuildprodlistcriteria();
         entity.whse = row.IsNull("whse") ? string.Empty : row.Field<string>("whse");
         entity.fromprod = row.IsNull("fromprod") ? string.Empty : row.Field<string>("fromprod");
         entity.toprod = row.IsNull("toprod") ? string.Empty : row.Field<string>("toprod");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         entity.recordcountlimit = row.IsNull("recordcountlimit") ? 0 : row.Field<int>("recordcountlimit");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromIcebbuildprodlistcriteria(ref DataRow row, Icebbuildprodlistcriteria entity)
      {
         row.SetField("whse", entity.whse);
         row.SetField("fromprod", entity.fromprod);
         row.SetField("toprod", entity.toprod);
         row.SetField("userfield", entity.userfield);
         row.SetField("recordcountlimit", entity.recordcountlimit);

      }
   
   }
}
#pragma warning restore 1591
