//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 6149 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using ServiceInterfaceClient.Attributes;

namespace Infor.Sxe.PO.Data.Models.Complex
{
   using Models.Pdspoetprint;
   using Models.Pdspoetprintglobals;

   public partial class AspoheaderPOETPrintLoadResponseAPI
   {
      public List<Poetprintreportlist> poetprintreportlist { get; set; }
      public Poetprintscreensingle poetprintscreensingle { get; set; }
      public Poetprintglobals poetprintglobals { get; set; }
 
    
      public AspoheaderPOETPrintLoadResponseAPI()
      {
         this.poetprintreportlist = new List<Poetprintreportlist>(); 

      }
   }
}
#pragma warning restore 1591
