//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.OE.Data.Models.Pdsgetcomplist
{
   [ModelName("Infor.Sxe.OE.Data.Models.Pdsgetcomplist.Getcomplistresults")]
   public partial class Getcomplistresults : ModelBase
   {
      [StringValidationAttribute]
      public string complist { get; set; }
      [StringValidationAttribute]
      public string labellist { get; set; }


      public static Getcomplistresults BuildGetcomplistresultsFromRow(DataRow row)
      {
         Getcomplistresults entity = new Getcomplistresults();
         entity.complist = row.IsNull("complist") ? string.Empty : row.Field<string>("complist");
         entity.labellist = row.IsNull("labellist") ? string.Empty : row.Field<string>("labellist");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromGetcomplistresults(ref DataRow row, Getcomplistresults entity)
      {
         row.SetField("complist", entity.complist);
         row.SetField("labellist", entity.labellist);

      }
   
   }
}
#pragma warning restore 1591
