//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using NLog;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.PV.Data.Adapters
{
   using com.infor.sxproxy.pvproxy;
   using com.infor.sxproxy.pvproxy.StrongTypesNS;
    
   using Models.PdsContext;
   using Models.PdspvApeba;

   public partial class PvApebaAdapter : AdapterBase<pdsContextDataSet>
   {
      private const string DataSetName = "pdspv_apeba";
      private PVProxyAppObject proxyAppObject;
      private readonly Tuple<string, string> pvApebaTableControlKey;
		
      private pdspv_apebaDataSet dataSet;
        
      public PvApebaAdapter(IProgressConnection connection) : base(connection)
      {
         try 
         {
            this.proxyAppObject = new PVProxyAppObject(connection.Connection);
            this.pdsContext = new pdsContextDataSet();
            this.dataSet = new pdspv_apebaDataSet() { DataSetName = DataSetName };
            this.pvApebaTableControlKey = this.dataSet.ttblpv_apeba.GetTableControlParametersKey();
            
            if (!this.tempTableControlParameters.ContainsKey(this.pvApebaTableControlKey))
            {
               this.CreateTableControlParameters(this.pvApebaTableControlKey);
            }
            this.OnCreated();
         }
         catch (Exception ex)
         {
            NLogLogger.ErrorException("Failed in adapter ", ex);
            ErrorReportingHelper.ReportProgramErrors($"Error in PvApebaAdapter constructor - {ex.Message}");
         }
      }
  
      partial void OnCreated();
    
      protected void FetchWhere(string where, int batchsize, string fldList)
      {
         NLogLoggerP.Trace("Fetchwhere - Pv_apebaproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               this.SetAndFetch(where, batchsize == 0 ? DefaultFetchWhereRowCount : batchsize, fldList);
               using (var poPv_apebaproxy = this.proxyAppObject.CreatePO_pv_apebaproxy())
               {
                  var cErrorMessage = string.Empty;
                  this.SetRequiredContextParameters();
                  poPv_apebaproxy.FetchWhere(ref this.pdsContext, out this.dataSet, out cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("Fetchwhere - Pv_apebaproxy - After Call");
      }
      
      private void SetAndFetch(string where, int batchsize, string fldList)
      {
         MappedDiagnosticsContext.Set("where", where);
         this.SetFetchWhereParameters(this.pvApebaTableControlKey, where, batchsize, fldList);
         this.SetTableParametersOnContext(this.pvApebaTableControlKey, true);
      }
  
      protected void SaveChanges()
      {
         NLogLoggerP.Trace("SaveChanges - Pv_apebaproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poPv_apebaproxy = this.proxyAppObject.CreatePO_pv_apebaproxy())
               {
                  this.SetRequiredContextParameters();
                  poPv_apebaproxy.SaveChanges(ref this.pdsContext, ref this.dataSet, out string cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("SaveChanges - Pv_apebaproxy - After Call");
      }
   

      public PvApeba GetByRowId(string rowId, string fldList)
      {
         var row = this.GetRowByRowId(rowId, fldList);
         PvApeba pvApeba = null;
         if (row != null)
         {
             pvApeba = this.BuildFromRow(row);
         }
         return pvApeba;
      }
   
      private DataRow GetRowByRowId(string rowId, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("rowid(pv_apeba) = to-rowid('0x{0}')", rowId.ToClauseString());
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttblpv_apeba.AsEnumerable().SingleOrDefault();
      }
        
      public IEnumerable<PvApeba> GetListByRowIdList(List<string> rowIds, int batchsize, string fldList)
      {
         var where = new StringBuilder();
         if (rowIds != null && rowIds.Count > 0)
         {
           foreach (var rowId in rowIds)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("rowid(pv_apeba)=to-rowid('0x{0}')", rowId.ToClauseString());
           }
         }
         return this.GetList(where.ToString(), batchsize, fldList);
      }

      protected PvApeba Fetch(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         var row = this.dataSet.ttblpv_apeba.AsEnumerable().SingleOrDefault();
         PvApeba pvApeba = null;
         if (row != null)
         {
             pvApeba = this.BuildFromRow(row);
         }
         return pvApeba;
      }
	  
	  
      public IEnumerable<PvApeba> GetListAllByCono(int cono, int batchsize, string fldList)
      {   
         cono = cono == 0 ? this.connection.CompanyNumber : cono;
         var sb = new StringBuilder();
         sb.AppendFormat("pv_apeba.cono = {0}", cono);
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<PvApeba> GetList(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         return (from DataRow row in this.dataSet.ttblpv_apeba.Rows where row != null select this.BuildFromRow(row)).ToList();
      }

      public PvApeba Get(int cono, string batchnm, int setno, int addonno, int pono, decimal posuf, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("pv_apeba.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(batchnm)) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.batchnm = '{0}'", batchnm);
         }
         if (setno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.setno = {0}", setno);
         }
         if (addonno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.addonno = {0}", addonno);
         }
         if (pono != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.pono = {0}", pono);
         }
         if (posuf != decimal.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.posuf = {0}", posuf);
         }
         var where = sb.ToString();
         return this.Fetch(where, batchsize, fldList);
      }
  
      public IEnumerable<PvApeba> GetListByStatus(int cono, bool statustype, decimal vendno, string apinvno, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("pv_apeba.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         sb.AppendFormatWithEscape(" AND pv_apeba.statustype = {0}", statustype);
         if (vendno != decimal.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.vendno = {0}", vendno);
         }
         if (!string.IsNullOrEmpty(apinvno)) 
         {
             sb.AppendFormatWithEscape(" AND pv_apeba.apinvno = '{0}'", apinvno);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public PvApeba BuildFromRow(DataRow row)
      {
         var returnRecord = PvApeba.BuildPvApebaFromRow(row);
         returnRecord = this.BuildExtraFromRow<PvApeba>(returnRecord, row);
         return returnRecord;
      }
      
      public void UpdateToRow(ref DataRow row, PvApeba record)
      {
         PvApeba.UpdateRowFromPvApeba(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
      }
      
      public PvApeba Insert(PvApeba record)
      {
         DataRow row = this.dataSet.ttblpv_apeba.Newttblpv_apebaRow();
         this.UpdateToRow(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
         this.dataSet.ttblpv_apeba.Addttblpv_apebaRow((pdspv_apebaDataSet.ttblpv_apebaRow)row);
         this.SaveChanges();
         return this.dataSet.ttblpv_apeba.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblpv_apeba.Rows[0]) : null;
      }
  

      public PvApeba Update(PvApeba record)
      {
        var row = this.GetRowByRowId(record.rowID, string.Empty);
         if (row != null)
         {
            this.UpdateToRow(ref row, record);
            this.ExtraUpdateToRow(ref row, record);
            this.SaveChanges();
            return this.dataSet.ttblpv_apeba.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblpv_apeba.Rows[0]) : null;
         }
         ErrorReportingHelper.ReportErrors("global.update.doesnotexist", 421);
         return null;
      }
  
      public void Delete(PvApeba record)
      {
         var row = this.GetRowByRowId(record.rowID, string.Empty);         
         if (row == null)
         {
            row = this.dataSet.ttblpv_apeba.Newttblpv_apebaRow();
            PvApeba.BuildMinimalRow(ref row, record);
            this.dataSet.ttblpv_apeba.Addttblpv_apebaRow((pdspv_apebaDataSet.ttblpv_apebaRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }

      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds != null)
         {
            var recList = rowIds.Select(selectRowId => new PvApeba() { rowID = selectRowId }).ToList();
            foreach (var rec in recList)
            {
               this.Delete(rec);
            }
         }
      }
	  

      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }	
         this.proxyAppObject?.Dispose();

         this.dataSet?.Dispose();
         base.Dispose(true);
      }
  
   }
}
#pragma warning restore 1591
  