//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using NLog;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.PO.Data.Adapters
{
   using com.infor.sxproxy.poproxy;
   using com.infor.sxproxy.poproxy.StrongTypesNS;
    
   using Models.PdsContext;
   using Models.Pdspoelb;

   public partial class PoelbAdapter : AdapterBase<pdsContextDataSet>
   {
      private const string DataSetName = "pdspoelb";
      private POProxyAppObject proxyAppObject;
      private readonly Tuple<string, string> poelbTableControlKey;
		
      private pdspoelbDataSet dataSet;
        
      public PoelbAdapter(IProgressConnection connection) : base(connection)
      {
         try 
         {
            this.proxyAppObject = new POProxyAppObject(connection.Connection);
            this.pdsContext = new pdsContextDataSet();
            this.dataSet = new pdspoelbDataSet() { DataSetName = DataSetName };
            this.poelbTableControlKey = this.dataSet.ttblpoelb.GetTableControlParametersKey();
            
            if (!this.tempTableControlParameters.ContainsKey(this.poelbTableControlKey))
            {
               this.CreateTableControlParameters(this.poelbTableControlKey);
            }
            this.OnCreated();
         }
         catch (Exception ex)
         {
            NLogLogger.ErrorException("Failed in adapter ", ex);
            ErrorReportingHelper.ReportProgramErrors($"Error in PoelbAdapter constructor - {ex.Message}");
         }
      }
  
      partial void OnCreated();
    
      protected void FetchWhere(string where, int batchsize, string fldList)
      {
         NLogLoggerP.Trace("Fetchwhere - Poelbproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               this.SetAndFetch(where, batchsize == 0 ? DefaultFetchWhereRowCount : batchsize, fldList);
               using (var poPoelbproxy = this.proxyAppObject.CreatePO_poelbproxy())
               {
                  var cErrorMessage = string.Empty;
                  this.SetRequiredContextParameters();
                  poPoelbproxy.FetchWhere(ref this.pdsContext, out this.dataSet, out cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("Fetchwhere - Poelbproxy - After Call");
      }
      
      private void SetAndFetch(string where, int batchsize, string fldList)
      {
         MappedDiagnosticsContext.Set("where", where);
         this.SetFetchWhereParameters(this.poelbTableControlKey, where, batchsize, fldList);
         this.SetTableParametersOnContext(this.poelbTableControlKey, true);
      }
  
      protected void SaveChanges()
      {
         NLogLoggerP.Trace("SaveChanges - Poelbproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poPoelbproxy = this.proxyAppObject.CreatePO_poelbproxy())
               {
                  this.SetRequiredContextParameters();
                  poPoelbproxy.SaveChanges(ref this.pdsContext, ref this.dataSet, out string cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("SaveChanges - Poelbproxy - After Call");
      }
   

      public Poelb GetByRowId(string rowId, string fldList)
      {
         var row = this.GetRowByRowId(rowId, fldList);
         Poelb poelb = null;
         if (row != null)
         {
             poelb = this.BuildFromRow(row);
         }
         return poelb;
      }
   
      private DataRow GetRowByRowId(string rowId, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("rowid(poelb) = to-rowid('0x{0}')", rowId.ToClauseString());
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttblpoelb.AsEnumerable().SingleOrDefault();
      }
        
      public IEnumerable<Poelb> GetListByRowIdList(List<string> rowIds, int batchsize, string fldList)
      {
         var where = new StringBuilder();
         if (rowIds != null && rowIds.Count > 0)
         {
           foreach (var rowId in rowIds)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("rowid(poelb)=to-rowid('0x{0}')", rowId.ToClauseString());
           }
         }
         return this.GetList(where.ToString(), batchsize, fldList);
      }

      protected Poelb Fetch(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         var row = this.dataSet.ttblpoelb.AsEnumerable().SingleOrDefault();
         Poelb poelb = null;
         if (row != null)
         {
             poelb = this.BuildFromRow(row);
         }
         return poelb;
      }
	  
	  
      public IEnumerable<Poelb> GetListAllByCono(int cono, int batchsize, string fldList)
      {   
         cono = cono == 0 ? this.connection.CompanyNumber : cono;
         var sb = new StringBuilder();
         sb.AppendFormat("poelb.cono = {0}", cono);
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Poelb> GetList(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         return (from DataRow row in this.dataSet.ttblpoelb.Rows where row != null select this.BuildFromRow(row)).ToList();
      }

      public Poelb Get(int cono, string shipmentid, int pono, int posuf, int lineno, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("poelb.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(shipmentid)) 
         {
             sb.AppendFormatWithEscape(" AND poelb.shipmentid = '{0}'", shipmentid);
         }
         if (pono != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.pono = {0}", pono);
         }
         if (posuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.posuf = {0}", posuf);
         }
         if (lineno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.lineno = {0}", lineno);
         }
         var where = sb.ToString();
         return this.Fetch(where, batchsize, fldList);
      }
  
      public IEnumerable<Poelb> GetListByPono(int cono, int pono, int posuf, int lineno, string shipmentid, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("poelb.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (pono != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.pono = {0}", pono);
         }
         if (posuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.posuf = {0}", posuf);
         }
         if (lineno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.lineno = {0}", lineno);
         }
         if (!string.IsNullOrEmpty(shipmentid)) 
         {
             sb.AppendFormatWithEscape(" AND poelb.shipmentid = '{0}'", shipmentid);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Poelb> GetListByProd(int cono, string shipmentid, int pono, int posuf, string shipprod, int lineno, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("poelb.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(shipmentid)) 
         {
             sb.AppendFormatWithEscape(" AND poelb.shipmentid = '{0}'", shipmentid);
         }
         if (pono != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.pono = {0}", pono);
         }
         if (posuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.posuf = {0}", posuf);
         }
         if (!string.IsNullOrEmpty(shipprod)) 
         {
             sb.AppendFormatWithEscape(" AND poelb.shipprod = '{0}'", shipprod);
         }
         if (lineno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND poelb.lineno = {0}", lineno);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public Poelb BuildFromRow(DataRow row)
      {
         var returnRecord = Poelb.BuildPoelbFromRow(row);
         returnRecord = this.BuildExtraFromRow<Poelb>(returnRecord, row);
         return returnRecord;
      }
      
      public void UpdateToRow(ref DataRow row, Poelb record)
      {
         Poelb.UpdateRowFromPoelb(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
      }
      
      public Poelb Insert(Poelb record)
      {
         DataRow row = this.dataSet.ttblpoelb.NewttblpoelbRow();
         this.UpdateToRow(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
         this.dataSet.ttblpoelb.AddttblpoelbRow((pdspoelbDataSet.ttblpoelbRow)row);
         this.SaveChanges();
         return this.dataSet.ttblpoelb.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblpoelb.Rows[0]) : null;
      }
  

      public Poelb Update(Poelb record)
      {
        var row = this.GetRowByRowId(record.rowID, string.Empty);
         if (row != null)
         {
            this.UpdateToRow(ref row, record);
            this.ExtraUpdateToRow(ref row, record);
            this.SaveChanges();
            return this.dataSet.ttblpoelb.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblpoelb.Rows[0]) : null;
         }
         ErrorReportingHelper.ReportErrors("global.update.doesnotexist", 421);
         return null;
      }
  
      public void Delete(Poelb record)
      {
         var row = this.GetRowByRowId(record.rowID, string.Empty);         
         if (row == null)
         {
            row = this.dataSet.ttblpoelb.NewttblpoelbRow();
            Poelb.BuildMinimalRow(ref row, record);
            this.dataSet.ttblpoelb.AddttblpoelbRow((pdspoelbDataSet.ttblpoelbRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }

      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds != null)
         {
            var recList = rowIds.Select(selectRowId => new Poelb() { rowID = selectRowId }).ToList();
            foreach (var rec in recList)
            {
               this.Delete(rec);
            }
         }
      }
	  

      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }	
         this.proxyAppObject?.Dispose();

         this.dataSet?.Dispose();
         base.Dispose(true);
      }
  
   }
}
#pragma warning restore 1591
  