//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 6149 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using ServiceInterfaceClient.Attributes;

namespace Infor.Sxe.SA.Data.Models.Complex
{
   using Models.Pdssasgaddonslists;
   using Models.Pdssasgaddonsresults;

   public partial class AssasetupSASGAddonsLoadResponseAPI
   {
      public List<Sasgaddonstaxability> sasgaddonstaxability { get; set; }
      public List<Sasgaddonstaxgroup> sasgaddonstaxgroup { get; set; }
      public List<Sasgaddonsresults> sasgaddonsresults { get; set; }
 
    
      public AssasetupSASGAddonsLoadResponseAPI()
      {
         this.sasgaddonstaxability = new List<Sasgaddonstaxability>(); 
         this.sasgaddonstaxgroup = new List<Sasgaddonstaxgroup>(); 
         this.sasgaddonsresults = new List<Sasgaddonsresults>(); 

      }
   }
}
#pragma warning restore 1591
