//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.PD.Data.Models.Pdspdemexcelimportnew
{
   [ModelName("Infor.Sxe.PD.Data.Models.Pdspdemexcelimportnew.Pdemexcelimportnewcriteria")]
   public partial class Pdemexcelimportnewcriteria : ModelBase
   {
      [StringValidationAttribute]
      public string cDestination { get; set; }
      [StringValidationAttribute]
      public string cImportFile { get; set; }
      public DateTime? dtStartDt { get; set; }
      public DateTime? dtEndDt { get; set; }
      [StringValidationAttribute]
      public string cWhse { get; set; }
      public bool lPriceRebFl { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Pdemexcelimportnewcriteria BuildPdemexcelimportnewcriteriaFromRow(DataRow row)
      {
         Pdemexcelimportnewcriteria entity = new Pdemexcelimportnewcriteria();
         entity.cDestination = row.IsNull("cDestination") ? string.Empty : row.Field<string>("cDestination");
         entity.cImportFile = row.IsNull("cImportFile") ? string.Empty : row.Field<string>("cImportFile");
         entity.dtStartDt = row.Field<DateTime?>("dtStartDt");
         entity.dtEndDt = row.Field<DateTime?>("dtEndDt");
         entity.cWhse = row.IsNull("cWhse") ? string.Empty : row.Field<string>("cWhse");
         entity.lPriceRebFl = row.Field<bool>("lPriceRebFl");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromPdemexcelimportnewcriteria(ref DataRow row, Pdemexcelimportnewcriteria entity)
      {
         row.SetField("cDestination", entity.cDestination);
         row.SetField("cImportFile", entity.cImportFile);
         row.SetField("dtStartDt", entity.dtStartDt);
         row.SetField("dtEndDt", entity.dtEndDt);
         row.SetField("cWhse", entity.cWhse);
         row.SetField("lPriceRebFl", entity.lPriceRebFl);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
