//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.PO.Data.Models.Pdsporrarreptupdate
{
   [ModelName("Infor.Sxe.PO.Data.Models.Pdsporrarreptupdate.Porrarreptupdatetotals")]
   public partial class Porrarreptupdatetotals : ModelBase
   {
      public decimal mergeamount { get; set; }
      public decimal mergecubes { get; set; }
      public decimal mergeweight { get; set; }
      public decimal mergeqtyordered { get; set; }
      public decimal totalamount { get; set; }
      public decimal totalcubes { get; set; }
      public decimal totalweight { get; set; }
      public decimal totalqtyordered { get; set; }


      public static Porrarreptupdatetotals BuildPorrarreptupdatetotalsFromRow(DataRow row)
      {
         Porrarreptupdatetotals entity = new Porrarreptupdatetotals();
         entity.mergeamount = row.IsNull("mergeamount") ? decimal.Zero : row.Field<decimal>("mergeamount");
         entity.mergecubes = row.IsNull("mergecubes") ? decimal.Zero : row.Field<decimal>("mergecubes");
         entity.mergeweight = row.IsNull("mergeweight") ? decimal.Zero : row.Field<decimal>("mergeweight");
         entity.mergeqtyordered = row.IsNull("mergeqtyordered") ? decimal.Zero : row.Field<decimal>("mergeqtyordered");
         entity.totalamount = row.IsNull("totalamount") ? decimal.Zero : row.Field<decimal>("totalamount");
         entity.totalcubes = row.IsNull("totalcubes") ? decimal.Zero : row.Field<decimal>("totalcubes");
         entity.totalweight = row.IsNull("totalweight") ? decimal.Zero : row.Field<decimal>("totalweight");
         entity.totalqtyordered = row.IsNull("totalqtyordered") ? decimal.Zero : row.Field<decimal>("totalqtyordered");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromPorrarreptupdatetotals(ref DataRow row, Porrarreptupdatetotals entity)
      {
         row.SetField("mergeamount", entity.mergeamount);
         row.SetField("mergecubes", entity.mergecubes);
         row.SetField("mergeweight", entity.mergeweight);
         row.SetField("mergeqtyordered", entity.mergeqtyordered);
         row.SetField("totalamount", entity.totalamount);
         row.SetField("totalcubes", entity.totalcubes);
         row.SetField("totalweight", entity.totalweight);
         row.SetField("totalqtyordered", entity.totalqtyordered);

      }
   
   }
}
#pragma warning restore 1591
