//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.KP.Data.Models.Pdskpiwloadheader
{
   [ModelName("Infor.Sxe.KP.Data.Models.Pdskpiwloadheader.Kpiwloadheadercriteria")]
   public partial class Kpiwloadheadercriteria : ModelBase
   {
      public int wono { get; set; }
      public int wosuf { get; set; }


      public static Kpiwloadheadercriteria BuildKpiwloadheadercriteriaFromRow(DataRow row)
      {
         Kpiwloadheadercriteria entity = new Kpiwloadheadercriteria();
         entity.wono = row.IsNull("wono") ? 0 : row.Field<int>("wono");
         entity.wosuf = row.IsNull("wosuf") ? 0 : row.Field<int>("wosuf");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromKpiwloadheadercriteria(ref DataRow row, Kpiwloadheadercriteria entity)
      {
         row.SetField("wono", entity.wono);
         row.SetField("wosuf", entity.wosuf);

      }
   
   }
}
#pragma warning restore 1591
