//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.TWL.Data.Models.Pdsemptranssummary
{
   [ModelName("Infor.Sxe.TWL.Data.Models.Pdsemptranssummary.Emptranssummary")]
   public partial class Emptranssummary : ModelBase
   {
      [StringValidationAttribute]
      public string dateTime { get; set; }
      [StringValidationAttribute]
      public string transType { get; set; }
      [StringValidationAttribute]
      public string transName { get; set; }
      public int numTrans { get; set; }
      [StringValidationAttribute]
      public string emptranssummaryuserfield { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Emptranssummary BuildEmptranssummaryFromRow(DataRow row)
      {
         Emptranssummary entity = new Emptranssummary();
         entity.dateTime = row.IsNull("date_time") ? string.Empty : row.Field<string>("date_time");
         entity.transType = row.IsNull("trans_type") ? string.Empty : row.Field<string>("trans_type");
         entity.transName = row.IsNull("trans_name") ? string.Empty : row.Field<string>("trans_name");
         entity.numTrans = row.IsNull("numTrans") ? 0 : row.Field<int>("numTrans");
         entity.emptranssummaryuserfield = row.IsNull("emptranssummaryuserfield") ? string.Empty : row.Field<string>("emptranssummaryuserfield");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromEmptranssummary(ref DataRow row, Emptranssummary entity)
      {
         row.SetField("date_time", entity.dateTime);
         row.SetField("trans_type", entity.transType);
         row.SetField("trans_name", entity.transName);
         row.SetField("numTrans", entity.numTrans);
         row.SetField("emptranssummaryuserfield", entity.emptranssummaryuserfield);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
