//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using NLog;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.OE.Data.Adapters
{
   using com.infor.sxproxy.oeproxy;
   using com.infor.sxproxy.oeproxy.StrongTypesNS;
    
   using Models.PdsContext;
   using Models.Pdsoeehc;

   public partial class OeehcAdapter : AdapterBase<pdsContextDataSet>
   {
      private const string DataSetName = "pdsoeehc";
      private OEProxyAppObject proxyAppObject;
      private readonly Tuple<string, string> oeehcTableControlKey;
		
      private pdsoeehcDataSet dataSet;
        
      public OeehcAdapter(IProgressConnection connection) : base(connection)
      {
         try 
         {
            this.proxyAppObject = new OEProxyAppObject(connection.Connection);
            this.pdsContext = new pdsContextDataSet();
            this.dataSet = new pdsoeehcDataSet() { DataSetName = DataSetName };
            this.oeehcTableControlKey = this.dataSet.ttbloeehc.GetTableControlParametersKey();
            
            if (!this.tempTableControlParameters.ContainsKey(this.oeehcTableControlKey))
            {
               this.CreateTableControlParameters(this.oeehcTableControlKey);
            }
            this.OnCreated();
         }
         catch (Exception ex)
         {
            NLogLogger.ErrorException("Failed in adapter ", ex);
            ErrorReportingHelper.ReportProgramErrors($"Error in OeehcAdapter constructor - {ex.Message}");
         }
      }
  
      partial void OnCreated();
    
      protected void FetchWhere(string where, int batchsize, string fldList)
      {
         NLogLoggerP.Trace("Fetchwhere - Oeehcproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               this.SetAndFetch(where, batchsize == 0 ? DefaultFetchWhereRowCount : batchsize, fldList);
               using (var poOeehcproxy = this.proxyAppObject.CreatePO_oeehcproxy())
               {
                  var cErrorMessage = string.Empty;
                  this.SetRequiredContextParameters();
                  poOeehcproxy.FetchWhere(ref this.pdsContext, out this.dataSet, out cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("Fetchwhere - Oeehcproxy - After Call");
      }
      
      private void SetAndFetch(string where, int batchsize, string fldList)
      {
         MappedDiagnosticsContext.Set("where", where);
         this.SetFetchWhereParameters(this.oeehcTableControlKey, where, batchsize, fldList);
         this.SetTableParametersOnContext(this.oeehcTableControlKey, true);
      }
  
      protected void SaveChanges()
      {
         NLogLoggerP.Trace("SaveChanges - Oeehcproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poOeehcproxy = this.proxyAppObject.CreatePO_oeehcproxy())
               {
                  this.SetRequiredContextParameters();
                  poOeehcproxy.SaveChanges(ref this.pdsContext, ref this.dataSet, out string cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("SaveChanges - Oeehcproxy - After Call");
      }
   

      public Oeehc GetByRowId(string rowId, string fldList)
      {
         var row = this.GetRowByRowId(rowId, fldList);
         Oeehc oeehc = null;
         if (row != null)
         {
             oeehc = this.BuildFromRow(row);
         }
         return oeehc;
      }
   
      private DataRow GetRowByRowId(string rowId, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("rowid(oeehc) = to-rowid('0x{0}')", rowId.ToClauseString());
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttbloeehc.AsEnumerable().SingleOrDefault();
      }
        
      public IEnumerable<Oeehc> GetListByRowIdList(List<string> rowIds, int batchsize, string fldList)
      {
         var where = new StringBuilder();
         if (rowIds != null && rowIds.Count > 0)
         {
           foreach (var rowId in rowIds)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("rowid(oeehc)=to-rowid('0x{0}')", rowId.ToClauseString());
           }
         }
         return this.GetList(where.ToString(), batchsize, fldList);
      }

      protected Oeehc Fetch(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         var row = this.dataSet.ttbloeehc.AsEnumerable().SingleOrDefault();
         Oeehc oeehc = null;
         if (row != null)
         {
             oeehc = this.BuildFromRow(row);
         }
         return oeehc;
      }
	  
	  
      public IEnumerable<Oeehc> GetListAllByCono(int cono, int batchsize, string fldList)
      {   
         cono = cono == 0 ? this.connection.CompanyNumber : cono;
         var sb = new StringBuilder();
         sb.AppendFormat("oeehc.cono = {0}", cono);
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Oeehc> GetList(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         return (from DataRow row in this.dataSet.ttbloeehc.Rows where row != null select this.BuildFromRow(row)).ToList();
      }

      public Oeehc Get(int cono, int orderno, int ordersuf, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("oeehc.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (orderno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.orderno = {0}", orderno);
         }
         if (ordersuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.ordersuf = {0}", ordersuf);
         }
         var where = sb.ToString();
         return this.Fetch(where, batchsize, fldList);
      }
  
      public IEnumerable<Oeehc> GetListByCreditmgr(int cono, string creditmgr, bool statustype, int priority, int orderno, int ordersuf, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("oeehc.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(creditmgr)) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.creditmgr = '{0}'", creditmgr);
         }
         sb.AppendFormatWithEscape(" AND oeehc.statustype = {0}", statustype);
         if (priority != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.priority = {0}", priority);
         }
         if (orderno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.orderno = {0}", orderno);
         }
         if (ordersuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.ordersuf = {0}", ordersuf);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Oeehc> GetListByCustno(int cono, decimal custno, bool statustype, int priority, int orderno, int ordersuf, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("oeehc.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (custno != decimal.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.custno = {0}", custno);
         }
         sb.AppendFormatWithEscape(" AND oeehc.statustype = {0}", statustype);
         if (priority != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.priority = {0}", priority);
         }
         if (orderno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.orderno = {0}", orderno);
         }
         if (ordersuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.ordersuf = {0}", ordersuf);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Oeehc> GetListByInq(int cono, bool statustype, int priority, int orderno, int ordersuf, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("oeehc.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         sb.AppendFormatWithEscape(" AND oeehc.statustype = {0}", statustype);
         if (priority != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.priority = {0}", priority);
         }
         if (orderno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.orderno = {0}", orderno);
         }
         if (ordersuf != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND oeehc.ordersuf = {0}", ordersuf);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public Oeehc BuildFromRow(DataRow row)
      {
         var returnRecord = Oeehc.BuildOeehcFromRow(row);
         returnRecord = this.BuildExtraFromRow<Oeehc>(returnRecord, row);
         return returnRecord;
      }
      
      public void UpdateToRow(ref DataRow row, Oeehc record)
      {
         Oeehc.UpdateRowFromOeehc(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
      }
      
      public Oeehc Insert(Oeehc record)
      {
         DataRow row = this.dataSet.ttbloeehc.NewttbloeehcRow();
         this.UpdateToRow(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
         this.dataSet.ttbloeehc.AddttbloeehcRow((pdsoeehcDataSet.ttbloeehcRow)row);
         this.SaveChanges();
         return this.dataSet.ttbloeehc.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttbloeehc.Rows[0]) : null;
      }
  

      public Oeehc Update(Oeehc record)
      {
        var row = this.GetRowByRowId(record.rowID, string.Empty);
         if (row != null)
         {
            this.UpdateToRow(ref row, record);
            this.ExtraUpdateToRow(ref row, record);
            this.SaveChanges();
            return this.dataSet.ttbloeehc.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttbloeehc.Rows[0]) : null;
         }
         ErrorReportingHelper.ReportErrors("global.update.doesnotexist", 421);
         return null;
      }
  
      public void Delete(Oeehc record)
      {
         var row = this.GetRowByRowId(record.rowID, string.Empty);         
         if (row == null)
         {
            row = this.dataSet.ttbloeehc.NewttbloeehcRow();
            Oeehc.BuildMinimalRow(ref row, record);
            this.dataSet.ttbloeehc.AddttbloeehcRow((pdsoeehcDataSet.ttbloeehcRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }

      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds != null)
         {
            var recList = rowIds.Select(selectRowId => new Oeehc() { rowID = selectRowId }).ToList();
            foreach (var rec in recList)
            {
               this.Delete(rec);
            }
         }
      }
	  

      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }	
         this.proxyAppObject?.Dispose();

         this.dataSet?.Dispose();
         base.Dispose(true);
      }
  
   }
}
#pragma warning restore 1591
  