//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.TWL.Data.Models.Pdsomopencounts
{
   [ModelName("Infor.Sxe.TWL.Data.Models.Pdsomopencounts.Opencountspriority")]
   public partial class Opencountspriority : ModelBase
   {
      [StringValidationAttribute]
      public string coNum { get; set; }
      [StringValidationAttribute]
      public string whNum { get; set; }
      public int iPriority { get; set; }
      public int iQty { get; set; }
      public int iLines { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Opencountspriority BuildOpencountspriorityFromRow(DataRow row)
      {
         Opencountspriority entity = new Opencountspriority();
         entity.coNum = row.IsNull("co_num") ? string.Empty : row.Field<string>("co_num");
         entity.whNum = row.IsNull("wh_num") ? string.Empty : row.Field<string>("wh_num");
         entity.iPriority = row.IsNull("i_priority") ? 0 : row.Field<int>("i_priority");
         entity.iQty = row.IsNull("i_qty") ? 0 : row.Field<int>("i_qty");
         entity.iLines = row.IsNull("i_lines") ? 0 : row.Field<int>("i_lines");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromOpencountspriority(ref DataRow row, Opencountspriority entity)
      {
         row.SetField("co_num", entity.coNum);
         row.SetField("wh_num", entity.whNum);
         row.SetField("i_priority", entity.iPriority);
         row.SetField("i_qty", entity.iQty);
         row.SetField("i_lines", entity.iLines);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
