//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using NLog;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.SA.Data.Adapters
{
   using com.infor.sxproxy.saproxy;
   using com.infor.sxproxy.saproxy.StrongTypesNS;
    
   using Models.PdsContext;
   using Models.Pdssapbj;

   public partial class SapbjAdapter : AdapterBase<pdsContextDataSet>
   {
      private const string DataSetName = "pdssapbj";
      private SAProxyAppObject proxyAppObject;
      private readonly Tuple<string, string> sapbjTableControlKey;
		
      private pdssapbjDataSet dataSet;
        
      public SapbjAdapter(IProgressConnection connection) : base(connection)
      {
         try 
         {
            this.proxyAppObject = new SAProxyAppObject(connection.Connection);
            this.pdsContext = new pdsContextDataSet();
            this.dataSet = new pdssapbjDataSet() { DataSetName = DataSetName };
            this.sapbjTableControlKey = this.dataSet.ttblsapbj.GetTableControlParametersKey();
            
            if (!this.tempTableControlParameters.ContainsKey(this.sapbjTableControlKey))
            {
               this.CreateTableControlParameters(this.sapbjTableControlKey);
            }
            this.OnCreated();
         }
         catch (Exception ex)
         {
            NLogLogger.ErrorException("Failed in adapter ", ex);
            ErrorReportingHelper.ReportProgramErrors($"Error in SapbjAdapter constructor - {ex.Message}");
         }
      }
  
      partial void OnCreated();
    
      protected void FetchWhere(string where, int batchsize, string fldList)
      {
         NLogLoggerP.Trace("Fetchwhere - Sapbjproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               this.SetAndFetch(where, batchsize == 0 ? DefaultFetchWhereRowCount : batchsize, fldList);
               using (var poSapbjproxy = this.proxyAppObject.CreatePO_sapbjproxy())
               {
                  var cErrorMessage = string.Empty;
                  this.SetRequiredContextParameters();
                  poSapbjproxy.FetchWhere(ref this.pdsContext, out this.dataSet, out cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("Fetchwhere - Sapbjproxy - After Call");
      }
      
      private void SetAndFetch(string where, int batchsize, string fldList)
      {
         MappedDiagnosticsContext.Set("where", where);
         this.SetFetchWhereParameters(this.sapbjTableControlKey, where, batchsize, fldList);
         this.SetTableParametersOnContext(this.sapbjTableControlKey, true);
      }
  
      protected void SaveChanges()
      {
         NLogLoggerP.Trace("SaveChanges - Sapbjproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poSapbjproxy = this.proxyAppObject.CreatePO_sapbjproxy())
               {
                  this.SetRequiredContextParameters();
                  poSapbjproxy.SaveChanges(ref this.pdsContext, ref this.dataSet, out string cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("SaveChanges - Sapbjproxy - After Call");
      }
   

      public Sapbj GetByRowId(string rowId, string fldList)
      {
         var row = this.GetRowByRowId(rowId, fldList);
         Sapbj sapbj = null;
         if (row != null)
         {
             sapbj = this.BuildFromRow(row);
         }
         return sapbj;
      }
   
      private DataRow GetRowByRowId(string rowId, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("rowid(sapbj) = to-rowid('0x{0}')", rowId.ToClauseString());
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttblsapbj.AsEnumerable().SingleOrDefault();
      }
        
      public IEnumerable<Sapbj> GetListByRowIdList(List<string> rowIds, int batchsize, string fldList)
      {
         var where = new StringBuilder();
         if (rowIds != null && rowIds.Count > 0)
         {
           foreach (var rowId in rowIds)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("rowid(sapbj)=to-rowid('0x{0}')", rowId.ToClauseString());
           }
         }
         return this.GetList(where.ToString(), batchsize, fldList);
      }

      protected Sapbj Fetch(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         var row = this.dataSet.ttblsapbj.AsEnumerable().SingleOrDefault();
         Sapbj sapbj = null;
         if (row != null)
         {
             sapbj = this.BuildFromRow(row);
         }
         return sapbj;
      }
	  
	  
      public IEnumerable<Sapbj> GetListAllByCono(int cono, int batchsize, string fldList)
      {   
         cono = cono == 0 ? this.connection.CompanyNumber : cono;
         var sb = new StringBuilder();
         sb.AppendFormat("sapbj.cono = {0}", cono);
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Sapbj> GetList(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         return (from DataRow row in this.dataSet.ttblsapbj.Rows where row != null select this.BuildFromRow(row)).ToList();
      }

      public Sapbj Get(int cono, string reportnm, int jrnlno, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("sapbj.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(reportnm)) 
         {
             sb.AppendFormatWithEscape(" AND sapbj.reportnm = '{0}'", reportnm);
         }
         if (jrnlno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND sapbj.jrnlno = {0}", jrnlno);
         }
         var where = sb.ToString();
         return this.Fetch(where, batchsize, fldList);
      }
  
      public IEnumerable<Sapbj> GetListBySeqno(int cono, string reportnm, int seqno, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("sapbj.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(reportnm)) 
         {
             sb.AppendFormatWithEscape(" AND sapbj.reportnm = '{0}'", reportnm);
         }
         if (seqno != int.MinValue) 
         {
             sb.AppendFormatWithEscape(" AND sapbj.seqno = {0}", seqno);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public Sapbj BuildFromRow(DataRow row)
      {
         var returnRecord = Sapbj.BuildSapbjFromRow(row);
         returnRecord = this.BuildExtraFromRow<Sapbj>(returnRecord, row);
         return returnRecord;
      }
      
      public void UpdateToRow(ref DataRow row, Sapbj record)
      {
         Sapbj.UpdateRowFromSapbj(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
      }
      
      public Sapbj Insert(Sapbj record)
      {
         DataRow row = this.dataSet.ttblsapbj.NewttblsapbjRow();
         this.UpdateToRow(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
         this.dataSet.ttblsapbj.AddttblsapbjRow((pdssapbjDataSet.ttblsapbjRow)row);
         this.SaveChanges();
         return this.dataSet.ttblsapbj.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblsapbj.Rows[0]) : null;
      }
  

      public Sapbj Update(Sapbj record)
      {
        var row = this.GetRowByRowId(record.rowID, string.Empty);
         if (row != null)
         {
            this.UpdateToRow(ref row, record);
            this.ExtraUpdateToRow(ref row, record);
            this.SaveChanges();
            return this.dataSet.ttblsapbj.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblsapbj.Rows[0]) : null;
         }
         ErrorReportingHelper.ReportErrors("global.update.doesnotexist", 421);
         return null;
      }
  
      public void Delete(Sapbj record)
      {
         var row = this.GetRowByRowId(record.rowID, string.Empty);         
         if (row == null)
         {
            row = this.dataSet.ttblsapbj.NewttblsapbjRow();
            Sapbj.BuildMinimalRow(ref row, record);
            this.dataSet.ttblsapbj.AddttblsapbjRow((pdssapbjDataSet.ttblsapbjRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }

      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds != null)
         {
            var recList = rowIds.Select(selectRowId => new Sapbj() { rowID = selectRowId }).ToList();
            foreach (var rec in recList)
            {
               this.Delete(rec);
            }
         }
      }
	  

      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }	
         this.proxyAppObject?.Dispose();

         this.dataSet?.Dispose();
         base.Dispose(true);
      }
  
   }
}
#pragma warning restore 1591
  