//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using NLog;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.SA.Data.Adapters
{
   using com.infor.sxproxy.saproxy;
   using com.infor.sxproxy.saproxy.StrongTypesNS;
    
   using Models.PdsContext;
   using Models.Pdssasta;
   using Models.Pdslookupcarrierresults;
   using Models.Complex;

   public partial class SastaAdapter : AdapterBase<pdsContextDataSet>
   {
      private const string DataSetName = "pdssasta";
      private SAProxyAppObject proxyAppObject;
      private readonly Tuple<string, string> sastaTableControlKey;
		
      private pdssastaDataSet dataSet;
        
      public SastaAdapter(IProgressConnection connection) : base(connection)
      {
         try 
         {
            this.proxyAppObject = new SAProxyAppObject(connection.Connection);
            this.pdsContext = new pdsContextDataSet();
            this.dataSet = new pdssastaDataSet() { DataSetName = DataSetName };
            this.sastaTableControlKey = this.dataSet.ttblsasta.GetTableControlParametersKey();
            
            if (!this.tempTableControlParameters.ContainsKey(this.sastaTableControlKey))
            {
               this.CreateTableControlParameters(this.sastaTableControlKey);
            }
            this.OnCreated();
         }
         catch (Exception ex)
         {
            NLogLogger.ErrorException("Failed in adapter ", ex);
            ErrorReportingHelper.ReportProgramErrors($"Error in SastaAdapter constructor - {ex.Message}");
         }
      }
  
      partial void OnCreated();
    
      protected void FetchWhere(string where, int batchsize, string fldList)
      {
         NLogLoggerP.Trace("Fetchwhere - Sastaproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               this.SetAndFetch(where, batchsize == 0 ? DefaultFetchWhereRowCount : batchsize, fldList);
               using (var poSastaproxy = this.proxyAppObject.CreatePO_sastaproxy())
               {
                  var cErrorMessage = string.Empty;
                  this.SetRequiredContextParameters();
                  poSastaproxy.FetchWhere(ref this.pdsContext, out this.dataSet, out cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("Fetchwhere - Sastaproxy - After Call");
      }
      
      private void SetAndFetch(string where, int batchsize, string fldList)
      {
         MappedDiagnosticsContext.Set("where", where);
         this.SetFetchWhereParameters(this.sastaTableControlKey, where, batchsize, fldList);
         this.SetTableParametersOnContext(this.sastaTableControlKey, true);
      }
  
      protected void SaveChanges()
      {
         NLogLoggerP.Trace("SaveChanges - Sastaproxy - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poSastaproxy = this.proxyAppObject.CreatePO_sastaproxy())
               {
                  this.SetRequiredContextParameters();
                  poSastaproxy.SaveChanges(ref this.pdsContext, ref this.dataSet, out string cErrorMessage);
                  ErrorReportingHelper.ReportErrors(cErrorMessage);
                  this.ReportErrors(this.pdsContext);
                  this.ReportErrors(this.dataSet);
               }
            });
         NLogLoggerP.Info("SaveChanges - Sastaproxy - After Call");
      }
   

      public Sasta GetByRowId(string rowId, string fldList)
      {
         var row = this.GetRowByRowId(rowId, fldList);
         Sasta sasta = null;
         if (row != null)
         {
             sasta = this.BuildFromRow(row);
         }
         return sasta;
      }
   
      private DataRow GetRowByRowId(string rowId, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("rowid(sasta) = to-rowid('0x{0}')", rowId.ToClauseString());
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttblsasta.AsEnumerable().SingleOrDefault();
      }
        
      public IEnumerable<Sasta> GetListByRowIdList(List<string> rowIds, int batchsize, string fldList)
      {
         var where = new StringBuilder();
         if (rowIds != null && rowIds.Count > 0)
         {
           foreach (var rowId in rowIds)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("rowid(sasta)=to-rowid('0x{0}')", rowId.ToClauseString());
           }
         }
         return this.GetList(where.ToString(), batchsize, fldList);
      }

      protected Sasta Fetch(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         var row = this.dataSet.ttblsasta.AsEnumerable().SingleOrDefault();
         Sasta sasta = null;
         if (row != null)
         {
             sasta = this.BuildFromRow(row);
         }
         return sasta;
      }
	  
	  
	  public IEnumerable<Sasta> GetListByRowpointers(List<string> rowpointers, string fldList)
      {
         var where = new StringBuilder();
         if (rowpointers != null && rowpointers.Count > 0)
         {
           foreach (var rowpointer in rowpointers)
           {
              if (where.ToString().Length > 0)
              {
                 where.Append(" OR ");
              }
              where.AppendFormat("sasta.rowpointer='{0}'", rowpointer);
           }
         }
         return this.GetList(where.ToString(), rowpointers.Count, fldList);
      }
	  
	  private DataRow GetRowByRowpointer(string rowpointer, string fldList)
      {
         var where = new StringBuilder();
         where.AppendFormat("sasta.rowpointer = '{0}'", rowpointer);
         this.FetchWhere(where.ToString(), 1, fldList);
         return this.dataSet.ttblsasta.AsEnumerable().SingleOrDefault();
      }
      public IEnumerable<Sasta> GetListAllByCono(int cono, int batchsize, string fldList)
      {   
         cono = cono == 0 ? this.connection.CompanyNumber : cono;
         var sb = new StringBuilder();
         sb.AppendFormat("sasta.cono = {0}", cono);
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public IEnumerable<Sasta> GetList(string where, int batchsize, string fldList)
      {
         this.FetchWhere(where, batchsize, fldList);
         return (from DataRow row in this.dataSet.ttblsasta.Rows where row != null select this.BuildFromRow(row)).ToList();
      }

      public Sasta Get(int cono, string codeiden, string codeval, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("sasta.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(codeiden)) 
         {
             sb.AppendFormatWithEscape(" AND sasta.codeiden = '{0}'", codeiden);
         }
         if (!string.IsNullOrEmpty(codeval)) 
         {
             sb.AppendFormatWithEscape(" AND sasta.codeval = '{0}'", codeval);
         }
         var where = sb.ToString();
         return this.Fetch(where, batchsize, fldList);
      }
  
      public IEnumerable<Sasta> GetListByDesc(int cono, string codeiden, string descrip, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         sb.AppendFormatWithEscape("sasta.cono = {0}", cono == 0 ? this.connection.CompanyNumber : cono);
         if (!string.IsNullOrEmpty(codeiden)) 
         {
             sb.AppendFormatWithEscape(" AND sasta.codeiden = '{0}'", codeiden);
         }
         if (!string.IsNullOrEmpty(descrip)) 
         {
             sb.AppendFormatWithEscape(" AND sasta.descrip = '{0}'", descrip);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public Sasta GetByRowpointer(string rowpointer, string fldList)
      {   
         var sb = new StringBuilder();
         if (!string.IsNullOrEmpty(rowpointer)) 
         {
             sb.AppendFormatWithEscape("sasta.rowpointer = '{0}'", rowpointer);
         }
         var where = sb.ToString();
         return this.Fetch(where, 1, fldList);
      }

      public IEnumerable<Sasta> GetListByTransdttmz(DateTime? transdttmz, int batchsize, string fldList)
      {   
         var sb = new StringBuilder();
         if (transdttmz != null) 
         {
             sb.AppendFormatWithEscape("sasta.transdttmz = '{0}'", transdttmz);
         }
         var where = sb.ToString();
         return this.GetList(where, batchsize, fldList);
      }

      public Sasta BuildFromRow(DataRow row)
      {
         var returnRecord = Sasta.BuildSastaFromRow(row);
         returnRecord = this.BuildExtraFromRow<Sasta>(returnRecord, row);
         return returnRecord;
      }
      
      public void UpdateToRow(ref DataRow row, Sasta record)
      {
         Sasta.UpdateRowFromSasta(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
      }
      
      public Sasta Insert(Sasta record)
      {
         DataRow row = this.dataSet.ttblsasta.NewttblsastaRow();
         this.UpdateToRow(ref row, record);
         this.ExtraUpdateToRow(ref row, record);
         this.dataSet.ttblsasta.AddttblsastaRow((pdssastaDataSet.ttblsastaRow)row);
         this.SaveChanges();
         return this.dataSet.ttblsasta.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblsasta.Rows[0]) : null;
      }
  

      public Sasta Update(Sasta record)
      {
        var row = this.GetRowByRowpointer(record.rowpointer, string.Empty);
         if (row != null)
         {
            this.UpdateToRow(ref row, record);
            this.ExtraUpdateToRow(ref row, record);
            this.SaveChanges();
            return this.dataSet.ttblsasta.Rows.Count > 0 ? this.BuildFromRow(this.dataSet.ttblsasta.Rows[0]) : null;
         }
         ErrorReportingHelper.ReportErrors("global.update.doesnotexist", 421);
         return null;
      }
  
      public void Delete(Sasta record)
      {
         var row = this.GetRowByRowpointer(record.rowpointer, string.Empty);         
         if (row == null)
         {
            row = this.dataSet.ttblsasta.NewttblsastaRow();
            Sasta.BuildMinimalRow(ref row, record);
            this.dataSet.ttblsasta.AddttblsastaRow((pdssastaDataSet.ttblsastaRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }
 
      private void DeleteUseRowID(Sasta record)
      {
         var row = this.GetRowByRowId(record.rowID, string.Empty);
         if (row == null)
         {
            row = this.dataSet.ttblsasta.NewttblsastaRow();
            Sasta.BuildMinimalRow(ref row, record);
            this.dataSet.ttblsasta.AddttblsastaRow((pdssastaDataSet.ttblsastaRow)row);
         }
         row.Delete();
         this.SaveChanges();
      }

      public void DeleteListByRowIds(List<string> rowIds)
      {
         if (rowIds != null)
         {
            var recList = rowIds.Select(selectRowId => new Sasta() { rowID = selectRowId }).ToList();
            foreach (var rec in recList)
            {
               this.DeleteUseRowID(rec);
            }
         }
      }
	  
 
      public void DeleteListByRowPointers(List<string> rowpointers)
      {
         if (rowpointers != null)
         {
            var recList = rowpointers.Select(selectRowpointer => new Sasta() { rowpointer = selectRowpointer }).ToList();
            foreach (var rec in recList)
            {
               this.Delete(rec);
            }
         }
      }

      public SastaLookupCarrierResponseAPI LookupCarrier(SastaLookupCarrierRequestAPI SastaLookupCarrierRequestAPI)
      {   
         var result = new SastaLookupCarrierResponseAPI();
         
         var pdslookupcarrierresults = new pdslookupcarrierresultsDataSet();
            
         string cErrorMessage = string.Empty;
         bool lMoreRecords = false;
   
         var  pvCodeval = SastaLookupCarrierRequestAPI.pvCodeval;
            
         var  pvRecordlimit = SastaLookupCarrierRequestAPI.pvRecordlimit;
            
         
         NLogLoggerP.Trace("LookupCarrier - Sasta - Before Call");
         StopwatchUtil.Time(
         () =>
            {
               using (var poSastaproxy = this.proxyAppObject.CreatePO_sastaproxy())
               {
                   this.SetRequiredContextParameters();
                   poSastaproxy.LookupCarrier(ref pdsContext,  pvCodeval,  pvRecordlimit, out pdslookupcarrierresults, out cErrorMessage, out lMoreRecords);
               }
            });
         NLogLoggerP.Info("LookupCarrier - Sasta - After Call");

         
         this.ReportErrors(cErrorMessage);
         this.ReportErrors(this.pdsContext);
         this.ReportErrors(pdslookupcarrierresults); 
    
         foreach (DataRow row in pdslookupcarrierresults.ttbllookupcarrierresults)
         {
            result.lookupcarrierresults.Add(Lookupcarrierresults.BuildLookupcarrierresultsFromRow(row));
         }     
         result.lMoreRecords = lMoreRecords;
          
         return result;
          
      }

      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }	
         this.proxyAppObject?.Dispose();

         this.dataSet?.Dispose();
         base.Dispose(true);
      }
  
   }
}
#pragma warning restore 1591
  