//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 21496 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.Collections.Generic;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Extensions;
using ServiceInterfaceClient.Interfaces;
using ServiceInterfaceClient.Progress;
    
namespace Infor.Sxe.AR.Data.Repositories
{
   using Infor.Sxe.AR.Data.Adapters;
   
   using Models.PdsContext;
   using Models.Pdsariccreatetrans;
   using Models.Pdsaricloadaretset;
   using Models.Pdsarilcriteria;
   using Models.Pdsarilbatchsingle;
   using Models.Pdsarilcheckresults;
   using Models.Pdsariltransresults;
   using Models.Pdsariltransmission;
   using Models.Pdsarilwocriteria;
   using Models.Pdsarilworesults;
   using Models.Pdsarsdlookup;
   using Models.Pdsarspdisplaytotals;
   using Models.Pdsbuildcustcredit;
   using Models.Pdscalccreditavail;
   using Models.Pdscustbaldisplay;
   using Models.Pdscustmessage;
   using Models.Pdscustpmtsdisplay;
   using Models.Pdsarshiptoaging;
   using Models.Pdsartransdetail;
   using Models.Pdsaricgrpdisp;
   using Models.Complex;

   public partial class AsarinquiryRepository : RepositoryBase
   {
      private AsarinquiryAdapter adapter;
  
      public AsarinquiryRepository(IProgressConnection connection)
      {
         this.adapter = new AsarinquiryAdapter(connection);
         this.Cono = this.adapter.Cono;
         this.OnCreated();
      }
  
      partial void OnCreated();
      
      public AsarinquiryARICCreateTransactionsResponseAPI ARICCreateTransactions(Ariccreatetranscriteria ariccreatetranscriteria)
      {
         return this.adapter.ARICCreateTransactions(ariccreatetranscriteria);
      }
  
      public IEnumerable<Aricloadaretsetresults> ARICLoadAretsetTT(Aricloadaretsetcriteria aricloadaretsetcriteria)
      {
         return this.adapter.ARICLoadAretsetTT(aricloadaretsetcriteria);
      }
  
      public Arilbatchsingle ARILBatchLoad(Arilcriteria arilcriteria)
      {
         return this.adapter.ARILBatchLoad(arilcriteria);
      }
  
      public IEnumerable<Arilcheckresults> ARILCheckLoad(Arilcriteria arilcriteria)
      {
         return this.adapter.ARILCheckLoad(arilcriteria);
      }
  
      public IEnumerable<Ariltransresults> ARILTransLoad(Arilcriteria arilcriteria)
      {
         return this.adapter.ARILTransLoad(arilcriteria);
      }
  
      public IEnumerable<Ariltransmissionresults> ARILTransmissionLoad(Ariltransmissioncriteria ariltransmissioncriteria)
      {
         return this.adapter.ARILTransmissionLoad(ariltransmissioncriteria);
      }
  
      public AsarinquiryARILWOLoadResponseAPI ARILWOLoad(Arilwocriteria arilwocriteria)
      {
         return this.adapter.ARILWOLoad(arilwocriteria);
      }
  
      public IEnumerable<Arsdlookupresults> ARSDlookup(Arsdlookupcriteria arsdlookupcriteria)
      {
         return this.adapter.ARSDlookup(arsdlookupcriteria);
      }
  
      public IEnumerable<Arspdisplaytotalsresults> ARSPDisplayTotals(Arspdisplaytotalscriteria arspdisplaytotalscriteria)
      {
         return this.adapter.ARSPDisplayTotals(arspdisplaytotalscriteria);
      }
  
      public IEnumerable<Buildcustcreditresults> BuildCustCreditTT(Buildcustcreditcriteria buildcustcreditcriteria)
      {
         return this.adapter.BuildCustCreditTT(buildcustcreditcriteria);
      }
  
      public Calccreditavailresults CalcOnOrderCreditAvail(Calccreditavailcriteria calccreditavailcriteria)
      {
         return this.adapter.CalcOnOrderCreditAvail(calccreditavailcriteria);
      }
  
      public IEnumerable<Custbaldisplayresults> CustBalDisplay(Custbaldisplaycriteria custbaldisplaycriteria)
      {
         return this.adapter.CustBalDisplay(custbaldisplaycriteria);
      }
  
      public Custmessageresults CustMessage(Custmessagecriteria custmessagecriteria)
      {
         return this.adapter.CustMessage(custmessagecriteria);
      }
  
      public Custpmtsdisplayresults CustPaymentsDisplay(Custpmtsdisplaycriteria custpmtsdisplaycriteria)
      {
         return this.adapter.CustPaymentsDisplay(custpmtsdisplaycriteria);
      }
  
      public IEnumerable<Arshiptoagingresults> ShipToAging(Arshiptoagingcriteria arshiptoagingcriteria)
      {
         return this.adapter.ShipToAging(arshiptoagingcriteria);
      }
  
      public Artransdetailresults ARTransactionDetail(Artransdetailcriteria artransdetailcriteria)
      {
         return this.adapter.ARTransactionDetail(artransdetailcriteria);
      }
  
      public Aricgrpdispresults AricGroupDisplay(Aricgrpdispcriteria aricgrpdispcriteria)
      {
         return this.adapter.AricGroupDisplay(aricgrpdispcriteria);
      }
  
      protected override void Dispose(bool disposing)
      {
         if (this.disposed) { return; }
         if (!disposing)
         {
            return;
         }
         this.adapter?.Dispose();	
         this.adapter = null;
         base.Dispose(true);
      }
   }
}
#pragma warning restore 1591
  