//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.PD.Data.Models.Pdspdemimportnewfile
{
   [ModelName("Infor.Sxe.PD.Data.Models.Pdspdemimportnewfile.Pdemimportnewexcelerrors")]
   public partial class Pdemimportnewexcelerrors : ModelBase
   {
      public int iRow { get; set; }
      public int iCol { get; set; }
      [StringValidationAttribute]
      public string cErrorMsg { get; set; }
      [StringValidationAttribute]
      public string cColor { get; set; }
      [StringValidationAttribute]
      public string cType { get; set; }
      [StringValidationAttribute]
      public string cColValues { get; set; }
      [StringValidationAttribute]
      public string cColLabels { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Pdemimportnewexcelerrors BuildPdemimportnewexcelerrorsFromRow(DataRow row)
      {
         Pdemimportnewexcelerrors entity = new Pdemimportnewexcelerrors();
         entity.iRow = row.IsNull("iRow") ? 0 : row.Field<int>("iRow");
         entity.iCol = row.IsNull("iCol") ? 0 : row.Field<int>("iCol");
         entity.cErrorMsg = row.IsNull("cErrorMsg") ? string.Empty : row.Field<string>("cErrorMsg");
         entity.cColor = row.IsNull("cColor") ? string.Empty : row.Field<string>("cColor");
         entity.cType = row.IsNull("cType") ? string.Empty : row.Field<string>("cType");
         entity.cColValues = row.IsNull("cColValues") ? string.Empty : row.Field<string>("cColValues");
         entity.cColLabels = row.IsNull("cColLabels") ? string.Empty : row.Field<string>("cColLabels");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromPdemimportnewexcelerrors(ref DataRow row, Pdemimportnewexcelerrors entity)
      {
         row.SetField("iRow", entity.iRow);
         row.SetField("iCol", entity.iCol);
         row.SetField("cErrorMsg", entity.cErrorMsg);
         row.SetField("cColor", entity.cColor);
         row.SetField("cType", entity.cType);
         row.SetField("cColValues", entity.cColValues);
         row.SetField("cColLabels", entity.cColLabels);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
