//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.GL.Data.Models.Pdsglsfsetuph
{
   [ModelName("Infor.Sxe.GL.Data.Models.Pdsglsfsetuph.Glsfsetuphtype")]
   public partial class Glsfsetuphtype : ModelBase
   {
      public int itemno { get; set; }
      [StringValidationAttribute]
      public string descr { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Glsfsetuphtype BuildGlsfsetuphtypeFromRow(DataRow row)
      {
         Glsfsetuphtype entity = new Glsfsetuphtype();
         entity.itemno = row.IsNull("itemno") ? 0 : row.Field<int>("itemno");
         entity.descr = row.IsNull("descr") ? string.Empty : row.Field<string>("descr");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromGlsfsetuphtype(ref DataRow row, Glsfsetuphtype entity)
      {
         row.SetField("itemno", entity.itemno);
         row.SetField("descr", entity.descr);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
