//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//     Template version $Rev: 13370 $
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     (c) Infor Global Solutions 2018
// 
//------------------------------------------------------------------------------

#pragma warning disable 1591
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using HelpPageErrorSimulator.HelpArea.Areas.HelpPage.ModelDescriptions;
using ServiceInterfaceClient.Attributes;
using ServiceInterfaceClient.BaseClasses;
using ServiceInterfaceClient.Helpers;
using ServiceInterfaceClient.Interfaces;

namespace Infor.Sxe.PD.Data.Models.Pdspdspwidget
{
   [ModelName("Infor.Sxe.PD.Data.Models.Pdspdspwidget.Pdspwidgetresults")]
   public partial class Pdspwidgetresults : ModelBase
   {
      public bool lContractNofl { get; set; }
      public bool lCustNamefl { get; set; }
      public bool lCustNofl { get; set; }
      public bool lCustPricetypefl { get; set; }
      public bool lCustPricetypedescfl { get; set; }
      public bool lCustRebtypefl { get; set; }
      public bool lCustRebtypedescfl { get; set; }
      public bool lPDRecnofl { get; set; }
      public bool lProdfl { get; set; }
      public bool lProdCatfl { get; set; }
      public bool lProdCatdescfl { get; set; }
      public bool lProddescfl { get; set; }
      public bool lProdLinefl { get; set; }
      public bool lProdLinedescfl { get; set; }
      public bool lProdPricetypefl { get; set; }
      public bool lProdPricetypedescfl { get; set; }
      public bool lRebTypefl { get; set; }
      public bool lRebTypedescfl { get; set; }
      public bool lShipTofl { get; set; }
      public bool lShipTonamefl { get; set; }
      public bool lStartdtfl { get; set; }
      public bool lSubRebtypefl { get; set; }
      public bool lSubRebtypedescfl { get; set; }
      public bool lUnitfl { get; set; }
      public bool lVendNamefl { get; set; }
      public bool lVendNofl { get; set; }
      public bool lWhsefl { get; set; }
      public bool lRegnFl { get; set; }
      public bool lWhseNamefl { get; set; }
      public bool lRegnNamefl { get; set; }
      public bool lRebatecdfl { get; set; }
      public bool lShiptypefl { get; set; }
      public int iSecurity { get; set; }
      public bool lUseContractvfl { get; set; }
      public bool lUseContractsfl { get; set; }
      public bool lUseRebSubTypefl { get; set; }
      public bool lManualfl { get; set; }
      public bool lContractlineno { get; set; }
      public bool lModelfl { get; set; }
      public bool lModeldescfl { get; set; }
      public bool lBrandfl { get; set; }
      public bool lBranddescfl { get; set; }
      public bool lCustGroupfl { get; set; }
      public bool lCustGroupdescfl { get; set; }
      public bool lPriceRebfl { get; set; }
      public bool lUsePricevfl { get; set; }
      [StringValidationAttribute]
      public string userfield { get; set; }


      public static Pdspwidgetresults BuildPdspwidgetresultsFromRow(DataRow row)
      {
         Pdspwidgetresults entity = new Pdspwidgetresults();
         entity.lContractNofl = row.Field<bool>("lContractNofl");
         entity.lCustNamefl = row.Field<bool>("lCustNamefl");
         entity.lCustNofl = row.Field<bool>("lCustNofl");
         entity.lCustPricetypefl = row.Field<bool>("lCustPricetypefl");
         entity.lCustPricetypedescfl = row.Field<bool>("lCustPricetypedescfl");
         entity.lCustRebtypefl = row.Field<bool>("lCustRebtypefl");
         entity.lCustRebtypedescfl = row.Field<bool>("lCustRebtypedescfl");
         entity.lPDRecnofl = row.Field<bool>("lPDRecnofl");
         entity.lProdfl = row.Field<bool>("lProdfl");
         entity.lProdCatfl = row.Field<bool>("lProdCatfl");
         entity.lProdCatdescfl = row.Field<bool>("lProdCatdescfl");
         entity.lProddescfl = row.Field<bool>("lProddescfl");
         entity.lProdLinefl = row.Field<bool>("lProdLinefl");
         entity.lProdLinedescfl = row.Field<bool>("lProdLinedescfl");
         entity.lProdPricetypefl = row.Field<bool>("lProdPricetypefl");
         entity.lProdPricetypedescfl = row.Field<bool>("lProdPricetypedescfl");
         entity.lRebTypefl = row.Field<bool>("lRebTypefl");
         entity.lRebTypedescfl = row.Field<bool>("lRebTypedescfl");
         entity.lShipTofl = row.Field<bool>("lShipTofl");
         entity.lShipTonamefl = row.Field<bool>("lShipTonamefl");
         entity.lStartdtfl = row.Field<bool>("lStartdtfl");
         entity.lSubRebtypefl = row.Field<bool>("lSubRebtypefl");
         entity.lSubRebtypedescfl = row.Field<bool>("lSubRebtypedescfl");
         entity.lUnitfl = row.Field<bool>("lUnitfl");
         entity.lVendNamefl = row.Field<bool>("lVendNamefl");
         entity.lVendNofl = row.Field<bool>("lVendNofl");
         entity.lWhsefl = row.Field<bool>("lWhsefl");
         entity.lRegnFl = row.Field<bool>("lRegnFl");
         entity.lWhseNamefl = row.Field<bool>("lWhseNamefl");
         entity.lRegnNamefl = row.Field<bool>("lRegnNamefl");
         entity.lRebatecdfl = row.Field<bool>("lRebatecdfl");
         entity.lShiptypefl = row.Field<bool>("lShiptypefl");
         entity.iSecurity = row.IsNull("iSecurity") ? 0 : row.Field<int>("iSecurity");
         entity.lUseContractvfl = row.Field<bool>("lUseContractvfl");
         entity.lUseContractsfl = row.Field<bool>("lUseContractsfl");
         entity.lUseRebSubTypefl = row.Field<bool>("lUseRebSubTypefl");
         entity.lManualfl = row.Field<bool>("lManualfl");
         entity.lContractlineno = row.Field<bool>("lContractlineno");
         entity.lModelfl = row.Field<bool>("lModelfl");
         entity.lModeldescfl = row.Field<bool>("lModeldescfl");
         entity.lBrandfl = row.Field<bool>("lBrandfl");
         entity.lBranddescfl = row.Field<bool>("lBranddescfl");
         entity.lCustGroupfl = row.Field<bool>("lCustGroupfl");
         entity.lCustGroupdescfl = row.Field<bool>("lCustGroupdescfl");
         entity.lPriceRebfl = row.Field<bool>("lPriceRebfl");
         entity.lUsePricevfl = row.Field<bool>("lUsePricevfl");
         entity.userfield = row.IsNull("userfield") ? string.Empty : row.Field<string>("userfield");
         return entity;
      }

      /// <summary>
      /// Update a database row from a class
      /// </summary>
      public static void UpdateRowFromPdspwidgetresults(ref DataRow row, Pdspwidgetresults entity)
      {
         row.SetField("lContractNofl", entity.lContractNofl);
         row.SetField("lCustNamefl", entity.lCustNamefl);
         row.SetField("lCustNofl", entity.lCustNofl);
         row.SetField("lCustPricetypefl", entity.lCustPricetypefl);
         row.SetField("lCustPricetypedescfl", entity.lCustPricetypedescfl);
         row.SetField("lCustRebtypefl", entity.lCustRebtypefl);
         row.SetField("lCustRebtypedescfl", entity.lCustRebtypedescfl);
         row.SetField("lPDRecnofl", entity.lPDRecnofl);
         row.SetField("lProdfl", entity.lProdfl);
         row.SetField("lProdCatfl", entity.lProdCatfl);
         row.SetField("lProdCatdescfl", entity.lProdCatdescfl);
         row.SetField("lProddescfl", entity.lProddescfl);
         row.SetField("lProdLinefl", entity.lProdLinefl);
         row.SetField("lProdLinedescfl", entity.lProdLinedescfl);
         row.SetField("lProdPricetypefl", entity.lProdPricetypefl);
         row.SetField("lProdPricetypedescfl", entity.lProdPricetypedescfl);
         row.SetField("lRebTypefl", entity.lRebTypefl);
         row.SetField("lRebTypedescfl", entity.lRebTypedescfl);
         row.SetField("lShipTofl", entity.lShipTofl);
         row.SetField("lShipTonamefl", entity.lShipTonamefl);
         row.SetField("lStartdtfl", entity.lStartdtfl);
         row.SetField("lSubRebtypefl", entity.lSubRebtypefl);
         row.SetField("lSubRebtypedescfl", entity.lSubRebtypedescfl);
         row.SetField("lUnitfl", entity.lUnitfl);
         row.SetField("lVendNamefl", entity.lVendNamefl);
         row.SetField("lVendNofl", entity.lVendNofl);
         row.SetField("lWhsefl", entity.lWhsefl);
         row.SetField("lRegnFl", entity.lRegnFl);
         row.SetField("lWhseNamefl", entity.lWhseNamefl);
         row.SetField("lRegnNamefl", entity.lRegnNamefl);
         row.SetField("lRebatecdfl", entity.lRebatecdfl);
         row.SetField("lShiptypefl", entity.lShiptypefl);
         row.SetField("iSecurity", entity.iSecurity);
         row.SetField("lUseContractvfl", entity.lUseContractvfl);
         row.SetField("lUseContractsfl", entity.lUseContractsfl);
         row.SetField("lUseRebSubTypefl", entity.lUseRebSubTypefl);
         row.SetField("lManualfl", entity.lManualfl);
         row.SetField("lContractlineno", entity.lContractlineno);
         row.SetField("lModelfl", entity.lModelfl);
         row.SetField("lModeldescfl", entity.lModeldescfl);
         row.SetField("lBrandfl", entity.lBrandfl);
         row.SetField("lBranddescfl", entity.lBranddescfl);
         row.SetField("lCustGroupfl", entity.lCustGroupfl);
         row.SetField("lCustGroupdescfl", entity.lCustGroupdescfl);
         row.SetField("lPriceRebfl", entity.lPriceRebfl);
         row.SetField("lUsePricevfl", entity.lUsePricevfl);
         row.SetField("userfield", entity.userfield);

      }
   
   }
}
#pragma warning restore 1591
